/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FeedUi: typeof import('./../src/widgets/feed/ui.vue')['default']
    FooterUi: typeof import('./../src/widgets/footer/ui.vue')['default']
    HeaderUi: typeof import('./../src/widgets/header/ui.vue')['default']
    ProfileUi: typeof import('./../src/widgets/profile/ui.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiIconCarousel: typeof import('./../src/shared/ui/icon/carousel.vue')['default']
    UiIconChart: typeof import('./../src/shared/ui/icon/chart.vue')['default']
    UiIconDots: typeof import('./../src/shared/ui/icon/dots.vue')['default']
    UiIconEdit: typeof import('./../src/shared/ui/icon/edit.vue')['default']
    UiIconHome: typeof import('./../src/shared/ui/icon/home.vue')['default']
    UiIconPhoto: typeof import('./../src/shared/ui/icon/photo.vue')['default']
    UiIconPushpin: typeof import('./../src/shared/ui/icon/pushpin.vue')['default']
    UiIconReels: typeof import('./../src/shared/ui/icon/reels.vue')['default']
    UiIconSearch: typeof import('./../src/shared/ui/icon/search.vue')['default']
    UiIconShare: typeof import('./../src/shared/ui/icon/share.vue')['default']
    UiIconShop: typeof import('./../src/shared/ui/icon/shop.vue')['default']
  }
}
