/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FooterUi: typeof import('./../src/widgets/footer/ui.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconIconCarousel: typeof import('./../src/components/icon/icon-carousel.vue')['default']
    IconIconChart: typeof import('./../src/components/icon/icon-chart.vue')['default']
    IconIconDots: typeof import('./../src/components/icon/icon-dots.vue')['default']
    IconIconEdit: typeof import('./../src/components/icon/icon-edit.vue')['default']
    IconIconHome: typeof import('./../src/components/icon/icon-home.vue')['default']
    IconIconPhoto: typeof import('./../src/components/icon/icon-photo.vue')['default']
    IconIconPushpin: typeof import('./../src/components/icon/icon-pushpin.vue')['default']
    IconIconReels: typeof import('./../src/components/icon/icon-reels.vue')['default']
    IconIconSearch: typeof import('./../src/components/icon/icon-search.vue')['default']
    IconIconShare: typeof import('./../src/components/icon/icon-share.vue')['default']
    IconIconShop: typeof import('./../src/components/icon/icon-shop.vue')['default']
    ProfileUi: typeof import('./../src/widgets/profile/ui.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiUiButton: typeof import('./../src/components/ui/ui-button.vue')['default']
    UiUiInput: typeof import('./../src/components/ui/ui-input.vue')['default']
    UiUiSearch: typeof import('./../src/components/ui/ui-search.vue')['default']
    WidgetsWidgetHeader: typeof import('./../src/components/widgets/widget-header.vue')['default']
  }
}
